// USER AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// USERS
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SELECTED_USER = "GET_SELECTED_USER";
// USER FILES
export const GET_FILES = "GET_FILES";
export const USER_FILE_DETAIL = "USER_FILE_DETAIL";
export const DELETE_USER_FILE = "DELETE_USER_FILE";
export const CREATE_USER_FILE = "CREATE_USER_FILE";
export const UPDATE_USER_FILE = "UPDATE_USER_FILE";
// USER FOLDERS
export const GET_FOLDERS = "GET_FOLDERS";
export const GET_SELECTED_FOLDER = "GET_SELECTED_FOLDER";
export const USER_FOLDER_DETAIL = "USER_FOLDER_DETAIL";
export const DELETE_USER_FOLDER = "DELETE_USER_FOLDER";
export const CREATE_USER_FOLDER = "CREATE_USER_FOLDER";
export const UPDATE_USER_FOLDER = "UPDATE_USER_FOLDER";
